services:
  hub:
    image: selenium/hub:4.8.0
    container_name: ddev-${DDEV_SITENAME}-hub
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}

  chrome:
    image: selenium/node-chrome:4.8.0
    container_name: ddev-${DDEV_SITENAME}-chrome
    shm_size: 256M
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
